### PR TITLE
Change license

### PR DESCRIPTION
**Pull request by skontar**
Based on CVSS SIG request, the license will be changed from GPLv3 to BSD-2-clause. All current contributors are asked to approve the change as current copyright holders.

### CODE REVIEW

**Comment by skontar** [comment]
Current contributors who need to approve license change:
-  @skontar / Stanislav Kontar
-  @ViperGeek / Dave Dugal 

Screenshot from 2023-06-02 18-18-34

**Comment by skontar** [comment]
I approve the license change.

**Comment by ViperGeek** [comment]
Approved

**Comment by skontar** [comment]
@ViperGeek I have updated the copyright notice to match intent of #29 . Please check if it matches your expectations, so I can merge it.

**Comment by ViperGeek** [comment]
> @ViperGeek I have updated the copyright notice to match intent of #29 . Please check if it matches your expectations, so I can merge it.

Looks good, @skontar!  Thanks for clarifying and updating the in-line copyright notice.  Please proceed.

**Pull request merged**
